#!/usr/bin/env python3

import json

# Write the rules to a JSON file

rules = [
  {
    "regexp": [r"([\s]{2,})"],
    "desc": "Extraneous Spaces detected"
  },
  {
    "regexp": [r"^(\,)", r"(\,)$", r"^\s*(and|or)\b", r"\b(the|to|by|on|or|and)\b$", r"^{\w*\}$"],
    "desc": "Sentence Fragments"
  },
  {
    "regexp": [r"(the\s*\{\w*\})", r"(a\s*\{\w*\})", r"(an\s*\{\w*\})", r"(a\(n\)\s*\{\w*\})"],
    "desc": "definite and indefinite articles before placeholders"
  },
  {
    "regexp": [r"(\{\w*\}\s*%)"],
    "desc": "percentage format"
  },
  {
    "regexp": [r"\'\{\'"],
    "desc": "Incorrect placeholder quoting."
  },
  {
    "regexp": [r"\{\w+\}\s*(year|month|week|day|hour|min|sec)",
               r"\{\w+\}\s*(groups|issues|users|people|other|boards|spaces)"],
    "desc": "Plural Nouns"
  },
  {
    "regexp": [r"(http|https)://", r"(<a\s*.*>\s*.*<\/a>)"],
    "desc": "String Resource contains URIs/URLs"
  },
  {
    "regexp": [r"\{\d+\}", r"\{\s*\}"],
    "desc": "Message contains numbered placeholders like \u2019{0}\u2019. Please use variable names in "
            "placeholders. "
  },
  {
    "regexp": [r"\{\s*\d\s*,\s*choice.+\}"],
    "desc": "Find string resources using the choice format"
  },
  {
    "regexp": [r"\'", r"\"", r"[\.]{3}"],
    "desc": "ASCII punctuation in use. Best Practice is to use their Unicode equivalents."
  },
  {
    "regexp": [r"^\s*$"],
    "desc": "empty string"
  }
]


def main():
    output_file = "lint_rules.json"
    with open(output_file, "w") as f:
        json.dump(rules, f, indent=4, sort_keys=False)
    print("Saved to \u2019{0}\u2019".format(output_file))


if __name__ == "__main__":
    main()
